color: null
description: null
fieldLayouts:
  4b9fe4e5-9e9a-40f8-8572-5d87c59d0035:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-18T21:12:38+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 83784b1e-9a07-4949-8518-4ed9053bc344
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d5e26aa2-7690-4bf2-81df-95fa6b771ade
        userCondition: null
handle: running
hasTitleField: true
icon: null
name: Running
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
