defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 3024dcee-b435-41ed-a4c0-b085497f4d68 # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  bcdd7152-a5b5-46bd-a1d3-f8d1bbd64472: # Kritik Patel
    enabledByDefault: true
    hasUrls: true
    template: homepage.twig
    uriFormat: __home__
type: single
