defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 2a4f3a53-b727-4b1d-be96-fc5046918b98 # Running
handle: running
maxAuthors: 1
name: Running
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  bcdd7152-a5b5-46bd-a1d3-f8d1bbd64472: # Kritik Patel
    enabledByDefault: true
    hasUrls: true
    template: running/_entry.twig
    uriFormat: 'running/{slug}'
type: channel
